In [ ]:
#pipinstall ipykernel==5.5.5

In [1]:
import torch
import numpy as np

In [3]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"


# 2d last dim

In [8]:
input = torch.arange(2*3).reshape(2, 3).float()

In [3]:
input

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [4]:
torch.mean(input, 1)

tensor([1., 4.])

In [12]:
torch.var(input, 1, unbiased=False)

tensor([0.6667, 0.6667])

In [4]:
m = torch.nn.LayerNorm(3)

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2021.1.2\plugins\python\helpers-pro\jupyter_debug\pydev_jupyter_utils.py", line 69, in attach_to_debugger
    debugger.prepare_to_run(enable_tracing_from_start=False)
TypeError: prepare_to_run() got an unexpected keyword argument 'enable_tracing_from_start'
Failed to connect to target debugger.


In [13]:
m(input)

tensor([[-1.2247,  0.0000,  1.2247],
        [-1.2247,  0.0000,  1.2247]], grad_fn=<NativeLayerNormBackward>)

In [14]:
(0 - 1) / np.sqrt(0.6667)

-1.2247142539179547

# 2d last 2 dim

In [2]:
m_1 = torch.nn.LayerNorm([2, 3])
print(m_1)

LayerNorm((2, 3), eps=1e-05, elementwise_affine=True)


In [14]:
m_1

LayerNorm((2, 3), eps=1e-05, elementwise_affine=True)

In [19]:
m_1(input)

tensor([[-1.4638, -0.8783, -0.2928],
        [ 0.2928,  0.8783,  1.4638]], grad_fn=<NativeLayerNormBackward>)

In [20]:
torch.mean(input)

tensor(2.5000)

In [21]:
torch.var(input, unbiased=False)

tensor(2.9167)

In [22]:
(0 - 2.5) / np.sqrt(2.9167)

-1.4638417446367296

# 4d 

In [24]:
input = torch.arange(2*3*4*5).reshape(2, 3, 4, 5).float()

In [25]:
input

tensor([[[[  0.,   1.,   2.,   3.,   4.],
          [  5.,   6.,   7.,   8.,   9.],
          [ 10.,  11.,  12.,  13.,  14.],
          [ 15.,  16.,  17.,  18.,  19.]],

         [[ 20.,  21.,  22.,  23.,  24.],
          [ 25.,  26.,  27.,  28.,  29.],
          [ 30.,  31.,  32.,  33.,  34.],
          [ 35.,  36.,  37.,  38.,  39.]],

         [[ 40.,  41.,  42.,  43.,  44.],
          [ 45.,  46.,  47.,  48.,  49.],
          [ 50.,  51.,  52.,  53.,  54.],
          [ 55.,  56.,  57.,  58.,  59.]]],


        [[[ 60.,  61.,  62.,  63.,  64.],
          [ 65.,  66.,  67.,  68.,  69.],
          [ 70.,  71.,  72.,  73.,  74.],
          [ 75.,  76.,  77.,  78.,  79.]],

         [[ 80.,  81.,  82.,  83.,  84.],
          [ 85.,  86.,  87.,  88.,  89.],
          [ 90.,  91.,  92.,  93.,  94.],
          [ 95.,  96.,  97.,  98.,  99.]],

         [[100., 101., 102., 103., 104.],
          [105., 106., 107., 108., 109.],
          [110., 111., 112., 113., 114.],
          [115., 116.,

In [27]:
m = torch.nn.LayerNorm([4, 5])

In [28]:
m(input)

tensor([[[[-1.6475, -1.4741, -1.3007, -1.1272, -0.9538],
          [-0.7804, -0.6070, -0.4336, -0.2601, -0.0867],
          [ 0.0867,  0.2601,  0.4336,  0.6070,  0.7804],
          [ 0.9538,  1.1272,  1.3007,  1.4741,  1.6475]],

         [[-1.6475, -1.4741, -1.3007, -1.1272, -0.9538],
          [-0.7804, -0.6070, -0.4336, -0.2601, -0.0867],
          [ 0.0867,  0.2601,  0.4336,  0.6070,  0.7804],
          [ 0.9538,  1.1272,  1.3007,  1.4741,  1.6475]],

         [[-1.6475, -1.4741, -1.3007, -1.1272, -0.9538],
          [-0.7804, -0.6070, -0.4336, -0.2601, -0.0867],
          [ 0.0867,  0.2601,  0.4336,  0.6070,  0.7804],
          [ 0.9538,  1.1272,  1.3007,  1.4741,  1.6475]]],


        [[[-1.6475, -1.4741, -1.3007, -1.1272, -0.9538],
          [-0.7804, -0.6070, -0.4336, -0.2601, -0.0867],
          [ 0.0867,  0.2601,  0.4336,  0.6070,  0.7804],
          [ 0.9538,  1.1272,  1.3007,  1.4741,  1.6475]],

         [[-1.6475, -1.4741, -1.3007, -1.1272, -0.9538],
          [-0.7804, -

In [29]:
torch.mean(input, [2, 3])

tensor([[  9.5000,  29.5000,  49.5000],
        [ 69.5000,  89.5000, 109.5000]])

In [30]:
torch.var(input, [2, 3], unbiased=False)

tensor([[33.2500, 33.2500, 33.2500],
        [33.2500, 33.2500, 33.2500]])

In [31]:
(0-9.5) / np.sqrt(33.25)

-1.647508942095828